apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Ingress","metadata":{"annotations":{"kubernetes.io/ingress.class":"nginx","kubernetes.io/ssl-redirect":"true"},"name":"reak-ingress","namespace":"ian"},"spec":{"rules":[{"host":"ian18ishar.sumpahpalapa.com","http":{"paths":[{"backend":{"serviceName":"app-svc","servicePort":80},"path":"/"}]}}],"tls":[{"secretName":"sumpahpalapa-certs"}]}}
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ssl-redirect: "true"
  creationTimestamp: "2020-06-06T13:36:11Z"
  generation: 2
  name: reak-ingress
  namespace: ian
  resourceVersion: "38425"
  selfLink: /apis/extensions/v1beta1/namespaces/ian/ingresses/reak-ingress
  uid: adc8cc67-3b49-4126-9df9-fa8f8f25d6e9
spec:
  rules:
  - host: ian18ishar.sumpahpalapa.com
    http:
      paths:
      - backend:
          serviceName: app-2048-service
          servicePort: 80
        path: /
  tls:
  - secretName: sumpahpalapa-certs
status:
  loadBalancer:
    ingress:
    - ip: 10.17.64.12
